version: "3.3"

services:
  app:
    build:
      context: ./svelte-app
      dockerfile: DockerFile.dev
    volumes:
      - ./svelte-app:/app
    ports:
      - "5432:5555"
  database:
    image: mongo:4.2
    restart: always
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    volumes:
      - mongodata:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8882
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@database:27017/
volumes:
  mongodata: